// Batch AA gate — "persistence and scale" (PASS_2026-09 rows G5, G7). RED-first on F18.62.
import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, DEMO, PDF, ROOT] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, close() { ws.close(); } })); ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } }); }); }
const port = 9250 + Math.floor(Math.random() * 40); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-paa-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable');
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + JSON.stringify(detail) : '')); };
const demo = readFileSync(DEMO, 'utf8'); const pdfB64 = readFileSync(PDF).toString('base64');
async function load(metrics, coarse) { if (metrics) await c.send('Emulation.setDeviceMetricsOverride', metrics); else await c.send('Emulation.clearDeviceMetricsOverride'); await c.send('Emulation.setTouchEmulationEnabled', { enabled: !!coarse, maxTouchPoints: 5 }); await c.send('Emulation.setEmulatedMedia', { features: coarse ? [{ name: 'pointer', value: 'coarse' }] : [] }); await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await ev(`window.print = () => {}; window.__demo = ${demo}; loadFromData.confirmed = true; window.confirmDocumentSwap = () => Promise.resolve(true); 1`); }
const state = () => ev(`({ rail: VESApp.state.railOpen, railClass: document.body.classList.contains('rail-collapsed'), pinned: !!VESApp.state.drawerPinned, pinnedClass: document.body.classList.contains('drawer-pinned'), fill: VESApp.state.fillMode || 'on', fillLabel: (document.querySelector('#btnFill .tl') || document.querySelector('#btnFills .tl') || {}).textContent, gridFt: document.getElementById('gridFt') && document.getElementById('gridFt').value, theme: document.documentElement.getAttribute('data-theme'), zoom: document.documentElement.style.zoom || '', scaleLabel: (document.getElementById('btnUiScale') || {}).textContent, prefs: (() => { try { return JSON.parse(localStorage.getItem('ves:prefs') || 'null'); } catch (_) { return 'unreadable'; } })() })`);
// ---- desktop: set every rest-state preference through the app's own doors, reload, expect them back
await load({ width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }, false);
await ev(`localStorage.removeItem('ves:prefs'); localStorage.removeItem('ves:theme'); 1`);
const s0 = await state();
const set = await ev(`(async () => { toggleRail(false); toggleDrawerPin(); cycleFills(); const g = document.getElementById('gridFt'); g.value = '5'; g.dispatchEvent(new Event('change', { bubbles: true })); g.dispatchEvent(new Event('input', { bubbles: true })); setTheme('light'); const sc = document.getElementById('btnUiScale'); if (sc) { sc.click(); sc.click(); } await new Promise(r => setTimeout(r, 200)); return true; })()`);
const s1 = await state();
await c.send('Page.reload'); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await sleep(300);
await ev(`window.print = () => {}; window.__demo = ${demo}; loadFromData.confirmed = true; window.confirmDocumentSwap = () => Promise.resolve(true); 1`);   // a reload is a fresh page: re-arm the seams
const s2 = await state();
check('AA1 rail collapsed, drawer pinned, fill mode, grid ft, theme and UI scale all come back after a reload', s2.rail === false && s2.railClass && s2.pinned && s2.pinnedClass && s2.fill === s1.fill && s1.fill !== 'on' && s2.gridFt === '5' && s2.theme === 'light' && !!s2.zoom && s2.zoom === s1.zoom && s1.zoom !== '' && s1.zoom !== '1', { before: s1, afterReload: s2 });
check('AA2 the preferences live in one store the app owns (ves:prefs), not in the takeoff', s2.prefs && typeof s2.prefs === 'object' && 'uiScale' in s2.prefs && 'rail' in s2.prefs, s2.prefs);
// ---- UI scale 1.5x: every lens still hittable and the sheet math still true
await ev(`typeof setUiScale === 'function' && setUiScale(1.5); 1`); await sleep(200);
const hit = await ev(`(async () => { const inV = (el) => { if (!el) return false; const r = el.getBoundingClientRect(); return r.width > 0 && r.left >= 0 && r.top >= 0 && r.right <= innerWidth && r.bottom <= innerHeight; };
  const out = { zoom: document.documentElement.style.zoom, toolbar: inV(document.getElementById('toolbar')), dataBtn: inV(document.getElementById('btnData') || document.querySelector('#dataMenuWrap button')) };
  VESApp.loadFromData(window.__demo); await new Promise(r => setTimeout(r, 400)); toggleRail(true);
  out.dock = inV(document.getElementById('dock')); VESApp.showEstimate(true); VESApp.renderEstimateGrid(); await new Promise(r => setTimeout(r, 200)); out.gridFoot = inV(document.getElementById('estgridFoot')); VESApp.showEstimate(false);
  setDataMenu(true); await new Promise(r => setTimeout(r, 100)); out.menu = inV(document.getElementById('dataMenu')); setDataMenu(false);
  VESApp.openDrawer(); VESApp.renderRecap(); await new Promise(r => setTimeout(r, 200)); out.drawer = inV(document.getElementById('drawerBody')); VESApp.collapseDrawer();
  await new Promise(r => requestAnimationFrame(() => setTimeout(r, 50))); const card = document.querySelector('#cards .card'); if (card && typeof showMoneyPeek === 'function') { showMoneyPeek(card); const pk = document.getElementById('moneyPeek'); const pr = pk.getBoundingClientRect(); out.peek = inV(pk); out.peekRect = [Math.round(pr.left), Math.round(pr.top), Math.round(pr.right), Math.round(pr.bottom)]; out.peekHidden = pk.hidden; out.cardRect = (() => { const q = card.getBoundingClientRect(); return [Math.round(q.left), Math.round(q.top), Math.round(q.right), Math.round(q.bottom)]; })(); hideMoneyPeek(); } else out.peek = false; return out; })()`);
check('AA3 at 1.5x UI scale on 1440x900: toolbar, exports door, dock, estimate footer, exports menu, recap panel and the money peek are all inside the viewport', hit.toolbar && hit.dataBtn && hit.dock && hit.gridFoot && hit.menu && hit.drawer && hit.peek, hit);
const trace = await ev(`(async () => { const u8 = new Uint8Array(await (await fetch('data:application/pdf;base64,${pdfB64}')).arrayBuffer()); await VESApp.openFromBytes(u8, 'plan.pdf'); let w = 0; while (!VESApp.AP().viewport && w < 30000) { await new Promise(r => setTimeout(r, 50)); w += 50; } await new Promise(r => setTimeout(r, 300));
  VESApp.applyScaleCalibration(VESApp.parseScale('1/8" = 1\\''), 1); VESApp.loadAssembly('tpo'); await new Promise(r => requestAnimationFrame(() => setTimeout(r, 100))); const cond = VESApp.state.conditions.find(x => x.libRef === 'tpo.dripedge'); VESApp.activateCondition(cond); await new Promise(r => setTimeout(r, 100));
  const p = VESApp.AP(); const o = p.els.overlay; const rect = o.getBoundingClientRect(); const pt = (x, y) => { const [vx, vy] = p.viewport.convertToViewportPoint(x, y); return { x: rect.left + vx, y: rect.top + vy }; };
  for (const q of [pt(300, 1500), pt(1300, 1500)]) o.dispatchEvent(new MouseEvent('click', { bubbles: true, clientX: q.x, clientY: q.y }));
  VESApp.finishDraft(); const m = VESApp.state.measurements[VESApp.state.measurements.length - 1]; return { zoom: document.documentElement.style.zoom, ft: m && +m.value.toFixed(2), type: m && m.type }; })()`);
check('AA4 at 1.5x UI scale a two-click trace of the 1000-unit line still reads 111.11 ft (pointer math holds under zoom)', trace.type === 'linear' && Math.abs(trace.ft - 111.11) < 1.5, trace);
await ev(`typeof setUiScale === 'function' && setUiScale(1); 1`);
// ---- phone: with no saved rail preference the narrow default still collapses; a saved "open" wins
await load({ width: 390, height: 844, deviceScaleFactor: 3, mobile: true }, true);
await ev(`localStorage.removeItem('ves:prefs'); 1`); await c.send('Page.reload'); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); }
const ph1 = await ev('VESApp.state.railOpen');
await ev(`toggleRail(true); 1`); await c.send('Page.reload'); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); }
const ph2 = await ev('VESApp.state.railOpen');
check('AA5 phone: no saved preference → rail rests collapsed; a saved "open" is honored on reload', ph1 === false && ph2 === true, { noPref: ph1, savedOpen: ph2 });
const fails = results.filter(r => !r.ok).length; console.log(`\nprobe-aa: ${results.length - fails}/${results.length} passed, ${fails} failed`); c.close(); chrome.kill('SIGKILL'); process.exit(fails ? 1 : 0);
