// Batch AD gate — the cheap candidates the personas left (T-05, T-06, G-10, G-12) plus the internal Estimate
// workbook with live formulas (bar M2, internal half). RED-first on F18.65.
import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, DEMO, ROOT] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, close() { ws.close(); } })); ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } }); }); }
const port = 9100 + Math.floor(Math.random() * 40); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-pad-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable');
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + JSON.stringify(detail) : '')); };
const demo = readFileSync(DEMO, 'utf8');
const arm = `window.print = () => { window.__printed = (window.__printed || 0) + 1; }; window.__demo = ${demo}; loadFromData.confirmed = true; window.confirmDocumentSwap = () => Promise.resolve(true); window.__blobs = []; window.saveBlob = (name, bytes, mime) => { window.__blobs.push({ name, bytes: (bytes instanceof Uint8Array) ? Array.from(bytes) : String(bytes), mime }); }; 1`;
async function load() { await c.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }); await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await ev(`localStorage.clear(); ${arm}`); await ev(`VESApp.loadFromData(window.__demo); VESApp.setProjectMeta({ name: 'Demo', preparedBy: { company: 'Synthetic Roofing Co', name: 'Sample Estimator' } }); 1`); await sleep(500); }
async function reload() { await c.send('Page.reload'); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await ev(arm); await sleep(300); }
const sheets = (bytes) => { const s = Buffer.from(bytes).toString('utf8'); const out = []; const re = /<worksheet[^>]*>([\s\S]*?)<\/worksheet>/g; let m; while ((m = re.exec(s)) !== null) out.push(m[1]); return out; };
const cells = (xml) => { const rows = []; const rr = /<row r="(\d+)">([\s\S]*?)<\/row>/g; let m; while ((m = rr.exec(xml)) !== null) { const row = {}; const cr = /<c r="([A-Z]+)\d+"([^>]*)>([\s\S]*?)<\/c>/g; let cm; while ((cm = cr.exec(m[2])) !== null) { const body = cm[3]; const f = /<f>([^<]*)<\/f>/.exec(body); const v = /<v>([^<]*)<\/v>/.exec(body); const t = /<t[^>]*>([^<]*)<\/t>/.exec(body); row[cm[1]] = { f: f ? f[1] : null, v: v ? +v[1] : null, t: t ? t[1] : null }; } rows.push(row); } return rows; };
await load();
// AD1 — the exports menu carries the client review door and the internal estimate workbook door
const menu = await ev(`(async () => { setDataMenu(true); await new Promise(r => setTimeout(r, 100)); const items = [...document.querySelectorAll('#dataMenu button')].map(b => ({ id: b.id, text: b.textContent.replace(/\\s+/g, ' ').trim(), visible: b.getBoundingClientRect().width > 0 })); setDataMenu(false); return items; })()`);
const rev = menu.find(i => /client review/i.test(i.text)), est = menu.find(i => /estimate.*xlsx|xlsx.*estimate/i.test(i.text));
check('AD1 the exports menu lists the client review .xlsx and an Estimate .xlsx (formulas) beside the CSVs', !!rev && rev.visible && !!est && est.visible, { rev, est });
// AD2 — the internal Estimate workbook: extension and ladder as live formulas that reproduce the recap
const ex = await ev(`(async () => { window.__blobs.length = 0; const b = document.getElementById('btnMenuEstimateXlsx'); if (b) b.click(); else if (typeof exportEstimateXLSX === 'function') exportEstimateXLSX(); await new Promise(r => setTimeout(r, 200)); const f = window.__blobs.find(x => /estimate.*\\.xlsx$/.test(x.name)); const m = VESApp.recapModel(); return { bytes: f ? f.bytes : null, name: f && f.name, cost: +m.cost.toFixed(2), sell: +m.sell.toFixed(2) }; })()`);
let ad2ok = false, ad2d = { name: ex.name };
if (ex.bytes) { const sh = sheets(ex.bytes); const rows = cells(sh[0] || ''); const hdr = rows[0] ? Object.values(rows[0]).map(x => x.t) : []; const extCol = Object.keys(rows[0] || {}).find(k => /extended|total/i.test(rows[0][k].t || '')); const lineFormulas = rows.slice(1).filter(r => r[extCol] && r[extCol].f && /\*/.test(r[extCol].f)).length; const labelCol = 'C'; const footer = {}; for (const r of rows) { const lab = r[labelCol] && r[labelCol].t; if (lab && /^(Cost|Overhead|Markup|Profit|Sell)/.test(lab)) footer[lab.split(' ')[0]] = r[extCol]; } const foot = Object.fromEntries(Object.entries(footer).map(([k, v]) => [k, { f: v && v.f, v: v && v.v }]));
  ad2d = { name: ex.name, hdr, lineFormulas, foot, recapCost: ex.cost, recapSell: ex.sell };
  ad2ok = lineFormulas >= 5 && foot.Cost && /SUM/i.test(foot.Cost.f || '') && foot.Sell && foot.Sell.f && Math.abs((foot.Sell.v || 0) - ex.sell) < 0.005 && Math.abs((foot.Cost.v || 0) - ex.cost) < 0.005 && ['Overhead', 'Markup', 'Profit'].every(k => foot[k] && foot[k].f); }
check('AD2 the Estimate .xlsx carries Qty×Unit formulas per line, SUM for Cost, ladder rows as formulas, and Sell as a formula whose cached value equals the recap sell', ad2ok, ad2d);
// AD3 — a print names itself on the toast (no stale text across a print)
const pr = await ev(`(async () => { toast('Supplier RFQ exported.', 'ok'); await new Promise(r => setTimeout(r, 50)); printCostSheet(); await new Promise(r => setTimeout(r, 120)); const t1 = document.getElementById('toast').textContent; printBidDoc(); document.getElementById('projModal').classList.remove('open'); printBidDoc(); await new Promise(r => setTimeout(r, 120)); const t2 = document.getElementById('toast').textContent; return { afterCostSheet: t1, afterBid: t2, printed: window.__printed || 0 }; })()`);
check('AD3 printing the cost sheet and the bid each set the toast to say what went to print (no stale export text)', /cost sheet/i.test(pr.afterCostSheet) && /bid/i.test(pr.afterBid) && pr.printed >= 2, pr);
// AD4 — the money peek has a keyboard door (a headless page fires focus events only when it believes it is focused)
await c.send('Emulation.setFocusEmulationEnabled', { enabled: true });
const kb = await ev(`(async () => { hideMoneyPeek(); const card = document.querySelector('#cards .card'); const b = card.querySelector('button'); b.focus(); await new Promise(r => setTimeout(r, 600)); const p = document.getElementById('moneyPeek'); const shown = !p.hidden && p.getBoundingClientRect().width > 0; b.blur(); await new Promise(r => setTimeout(r, 200)); const hiddenAfter = p.hidden; return { shown, hiddenAfter }; })()`);
check('AD4 focusing a card control shows the money peek after the same beat; leaving hides it', kb.shown && kb.hiddenAfter, kb);
// AD5 — dock width, snap, and split mode persist across a reload
const before = await ev(`(async () => { toggleSnap(); VESApp.setMode('split'); document.documentElement.style.setProperty('--dock-w', '480px'); if (typeof savePref === 'function' && typeof persistDockWidth === 'function') persistDockWidth(480); await new Promise(r => setTimeout(r, 150)); return { snap: VESApp.state.snap, mode: VESApp.state.mode, dockW: getComputedStyle(document.documentElement).getPropertyValue('--dock-w').trim() }; })()`);
await reload();
await ev(`VESApp.loadFromData(window.__demo); 1`); await sleep(500);   // split mode is applied once a sheet exists
const after = await ev(`({ snap: VESApp.state.snap, mode: VESApp.state.mode, dockW: getComputedStyle(document.documentElement).getPropertyValue('--dock-w').trim(), prefs: (() => { try { return JSON.parse(localStorage.getItem('ves:prefs') || 'null'); } catch (_) { return null; } })() })`);
check('AD5 snap, split mode and the dock width come back after a reload', after.snap === before.snap && after.mode === 'split' && after.dockW === '480px', { before, after });
const fails = results.filter(r => !r.ok).length; console.log(`\nprobe-ad: ${results.length - fails}/${results.length} passed, ${fails} failed`); c.close(); chrome.kill('SIGKILL'); process.exit(fails ? 1 : 0);
