// Batch V gate: RED on F18.58, must be GREEN on the patched build. Zero deps; raw CDP.
import { spawn, spawnSync } from 'node:child_process'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { inflateSync } from 'node:zlib';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, DEMO, PDF, ROOT] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map();
  ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, close() { ws.close(); } }));
  ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } }); }); }
const port = 9400 + Math.floor(Math.random() * 90); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-pv-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 150 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable');
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const demo = readFileSync(DEMO, 'utf8'); const pdfB64 = readFileSync(PDF).toString('base64');
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok, detail }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + JSON.stringify(detail) : '')); };
async function load(metrics, coarse) { if (metrics) await c.send('Emulation.setDeviceMetricsOverride', metrics); else await c.send('Emulation.clearDeviceMetricsOverride'); await c.send('Emulation.setTouchEmulationEnabled', { enabled: !!coarse, maxTouchPoints: 5 }); await c.send('Emulation.setEmulatedMedia', { features: coarse ? [{ name: 'pointer', value: 'coarse' }, { name: 'hover', value: 'none' }] : [] });
  await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 300; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await ev(`window.print = () => {}; window.__demo = ${demo}; loadFromData.confirmed = true; 1`); await sleep(300); }
// ---- desktop
await load({ width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }, false);
check('V0 build stamp is F18.59', (await ev('VESApp.VES_BUILD')) === 'F18.59', await ev('VESApp.VES_BUILD'));
check('V1 landing data-safety sentence names autosaved takeoffs', await ev(`/autosav/i.test(document.querySelector('.empty-safe').textContent)`));
const ctrl = await ev(`(async () => { VESApp.loadFromData(window.__demo); await new Promise(r => setTimeout(r, 400)); return +VESApp.recapModel().sell.toFixed(2); })()`);
check('V2 control: demo sell on desktop is 64620.46', ctrl === 64620.46, ctrl);
const ing = await ev(`(async () => { const d = JSON.parse(JSON.stringify(window.__demo)); d.measurements[0].value = "3150.8"; d.measurements[1].value = "abc"; d.conditions[0].pitch = "1.2"; d.conditions[1].unitCost = "12"; d.measurements.push({ id: 99, conditionId: 5, page: null, type: 'linear', points: "nope", value: 10, notes: '', manual: true }); VESApp.loadFromData(d); await new Promise(r => setTimeout(r, 500));
  return { sell: +VESApp.recapModel().sell.toFixed(2), toast: document.getElementById('toast').textContent, banner: [...document.querySelectorAll('.banner .msg')].map(b => b.textContent).join(' | '), meas: VESApp.state.measurements.length, unitCost: VESApp.state.conditions[1].unitCost, pitch: VESApp.state.conditions[0].pitch }; })()`);
check('V3a ingress: a string quantity is DROPPED, never priced as zero (both bad measurements and the bad-points one gone; nothing left to price)', ing.sell === 0 && ing.meas === 0, ing);
check('V3b ingress: the drop is said in the load toast AND a standing banner', /dropped|DROPPED|refused/i.test(ing.toast) && /dropped|DROPPED|refused/i.test(ing.banner), { toast: ing.toast.slice(0, 120), banner: ing.banner.slice(0, 120) });
check('V3c ingress: a string unitCost / pitch does not survive into state', ing.unitCost === null && (ing.pitch === undefined || ing.pitch === null || typeof ing.pitch === 'number'), { unitCost: ing.unitCost, pitch: ing.pitch });
// proposal legend colors under Chrome's default print (no background graphics)
const ph = await ev(`(async () => { const d = JSON.parse(JSON.stringify(window.__demo)); d.measurements = [{ id: 11, conditionId: 1, page: 1, type: 'area', points: [{x:20,y:20},{x:120,y:20},{x:120,y:90},{x:20,y:90}], value: 7000, notes: '', manual: false }, { id: 12, conditionId: 5, page: 1, type: 'linear', points: [{x:20,y:20},{x:120,y:20}], value: 100, notes: '', manual: false }]; VESApp.loadFromData(d); await new Promise(r => setTimeout(r, 600)); return await VESApp.proposalHTML(); })()`);
async function pdfFills(html, printBackground) { const { targetId } = await c.send('Target.createTarget', { url: 'about:blank' }); const list = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const t = list.find((x) => x.id === targetId); const c2 = await connect(t.webSocketDebuggerUrl); await c2.send('Page.enable'); await c2.send('Page.navigate', { url: 'data:text/html;base64,' + Buffer.from(html).toString('base64') }); await sleep(700); const { data } = await c2.send('Page.printToPDF', { printBackground, preferCSSPageSize: true }); const txt = Buffer.from(data, 'base64').toString('latin1'); const rg = new Set(); let m; const re = /stream\r?\n([\s\S]*?)endstream/g; while ((m = re.exec(txt)) !== null) { let dec; try { dec = inflateSync(Buffer.from(m[1], 'latin1')).toString('latin1'); } catch (_) { dec = m[1]; } for (const mm of dec.matchAll(/([0-9.]+) ([0-9.]+) ([0-9.]+) rg/g)) rg.add(mm.slice(1, 4).map((x) => (+x).toFixed(2)).join(',')); } c2.close(); await c.send('Target.closeTarget', { targetId }); return [...rg]; }
const fillsOff = await pdfFills(ph, false);
check('V4 proposal legend swatch colors survive printing WITHOUT background graphics', fillsOff.includes('1.00,0.36,0.23') && fillsOff.includes('0.69,0.49,0.85'), fillsOff);
// ---- phone portrait, coarse pointer
await load({ width: 390, height: 844, deviceScaleFactor: 3, mobile: true }, true);
const rest = await ev(`(async () => { const bin = atob('${pdfB64}'); const u8 = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i); await VESApp.openFromBytes(u8, 'synthetic-plan.pdf'); let w = 0; while (!VESApp.AP().viewport && w < 30000) { await new Promise(r => setTimeout(r, 50)); w += 50; } await new Promise(r => setTimeout(r, 300)); const p = VESApp.AP(); const wr = p.els.wrap.getBoundingClientRect(); return { coarse: matchMedia('(pointer: coarse)').matches, railOpen: VESApp.state.railOpen, wrapW: Math.round(wr.width), reopenVisible: !!(document.getElementById('railReopen') && document.getElementById('railReopen').offsetParent) }; })()`);
check('V5 phone at rest: the sheet column is at least 300 px wide (rail collapsed by default under 720 px)', rest.wrapW >= 300, rest);
check('V5b phone at rest: the rail is one tap away (reopen control visible)', rest.reopenVisible, rest);
const z2 = await ev(`(async () => { const p = VESApp.AP(); VESApp.setZoom(p, 2); let w = 0; while ((p.renderTask || !p.viewport || Math.abs(p.viewport.scale - 2) > 0.001) && w < 60000) { await new Promise(r => setTimeout(r, 50)); w += 50; } const cv = p.els.canvas; return { mp: +((cv.width * cv.height) / 1e6).toFixed(1), ms: w }; })()`);
check('V6 phone: 200% zoom raster capped at 16 MP on a coarse pointer', z2.mp <= 16.1, z2);
await ev(`(async () => { VESApp.loadAssembly('tpo'); VESApp.addManualQuantity('tpo.field', 3150.8); VESApp.showEstimate(true); VESApp.renderEstimateGrid(); await new Promise(r => setTimeout(r, 250)); })()`);
const cells = await ev(`(() => { const hs = [...document.querySelectorAll('#estgridBody input.recap-edit')].map(i => i.getBoundingClientRect().height); return { n: hs.length, min: Math.round(Math.min(...hs)) }; })()`);
check('V7 coarse pointer: estimate-grid money cells are at least 40 px tall', cells.n > 0 && cells.min >= 40, cells);
await ev('VESApp.showEstimate(false)');
const menu = await ev(`(async () => { setDataMenu(true); await new Promise(r => setTimeout(r, 100)); const hs = [...document.querySelectorAll('#dataMenu button')].filter(b => b.offsetParent).map(b => b.getBoundingClientRect().height); const r = document.getElementById('dataMenu').getBoundingClientRect(); setDataMenu(false); return { min: Math.round(Math.min(...hs)), n: hs.length, fits: r.top >= 0 && r.bottom <= innerHeight }; })()`);
check('V8 coarse pointer: exports-menu items are at least 40 px tall', menu.n > 0 && menu.min >= 40, menu);
// ---- phone landscape
await load({ width: 844, height: 390, deviceScaleFactor: 3, mobile: true }, true);
const land = await ev(`(async () => { setDataMenu(true); await new Promise(r => setTimeout(r, 100)); const m = document.getElementById('dataMenu'); const r = m.getBoundingClientRect(); const out = { top: Math.round(r.top), bottom: Math.round(r.bottom), innerHeight, scrolls: getComputedStyle(m).overflowY, fits: r.top >= 0 && r.bottom <= innerHeight }; setDataMenu(false); return out; })()`);
check('V9 landscape phone: exports menu stays inside the viewport (scrolls within itself)', land.fits, land);
// ---- verifier: freeze regions fenced (manifest may be absent)
const vr = spawnSync(process.execPath, [join(ROOT, 'tools/ves-verify.mjs'), '--json'], { encoding: 'utf8' }); let vj = null; try { vj = JSON.parse(vr.stdout); } catch (_) {}
check('V10 verifier sees two freeze regions (core + engine) fenced', vj && vj.freeze && vj.freeze.regions === 2, vj && vj.freeze);
check('V11 verifier RESULT PASS with 0 new egress', vj && vj.ok && vj.egress.added.length === 0, vj && { ok: vj.ok, added: vj.egress.added.length });
const fails = results.filter(r => !r.ok).length; console.log(`\nprobe-v: ${results.length - fails}/${results.length} passed, ${fails} failed`); c.close(); chrome.kill('SIGKILL'); process.exit(fails ? 1 : 0);
