// Batch AB gate — the P-TRADE / P-MARKET money-honesty rows: the client review sheet carries SELL and sums to the bid;
// a takeoff file names the library it was priced with and a mismatch is said; the estimate CSV shows the ladder;
// the landing and README name the audit trail. RED-first on F18.64.
import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, DEMO, ROOT] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, close() { ws.close(); } })); ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } }); }); }
const port = 9150 + Math.floor(Math.random() * 40); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-pab-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable');
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + JSON.stringify(detail) : '')); };
const demo = readFileSync(DEMO, 'utf8');
async function load() { await c.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }); await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await ev(`localStorage.clear(); window.print = () => {}; window.__demo = ${demo}; loadFromData.confirmed = true; window.confirmDocumentSwap = () => Promise.resolve(true); window.__blobs = []; window.saveBlob = (name, bytes, mime) => { window.__blobs.push({ name, bytes: (bytes instanceof Uint8Array) ? Array.from(bytes) : String(bytes), mime }); }; VESApp.loadFromData(window.__demo); VESApp.setProjectMeta({ name: 'Demo', preparedBy: { company: 'Synthetic Roofing Co', name: 'Sample Estimator' } }); 1`); await sleep(500); }
// helpers: the XLSX writer stores entries uncompressed, so the sheet XML is readable in the raw bytes
const sheets = (bytes) => { const s = Buffer.from(bytes).toString('utf8'); const out = []; const re = /<worksheet[^>]*>([\s\S]*?)<\/worksheet>/g; let m; while ((m = re.exec(s)) !== null) out.push(m[1]); return out; };
const cells = (xml) => { const rows = []; const rr = /<row r="(\d+)">([\s\S]*?)<\/row>/g; let m; while ((m = rr.exec(xml)) !== null) { const row = {}; const cr = /<c r="([A-Z]+)\d+"([^>]*)>([\s\S]*?)<\/c>/g; let cm; while ((cm = cr.exec(m[2])) !== null) { const body = cm[3]; const f = /<f>([^<]*)<\/f>/.exec(body); const v = /<v>([^<]*)<\/v>/.exec(body); const t = /<t[^>]*>([^<]*)<\/t>/.exec(body); row[cm[1]] = { f: f ? f[1] : null, v: v ? +v[1] : null, t: t ? t[1] : null }; } rows.push(row); } return rows; };
await load();
// AB1 — client review sheet in SELL, summing to the bid Total, with formulas for the sums
const ab1 = await ev(`(() => { printBidDoc(); document.getElementById('projModal').classList.remove('open'); printBidDoc(); const total = (document.querySelector('#printDoc .total-line .n') || {}).textContent; const rows = [...document.querySelectorAll('#printDoc .divblock tbody tr')].filter(r => !r.classList.contains('grand')).map(r => [...r.children].map(x => x.textContent.trim())); window.__blobs.length = 0; exportClientReviewXLSX(); const b = window.__blobs.find(x => /client-review\\.xlsx$/.test(x.name)); return { bidTotal: total, bidRows: rows, bytes: b ? b.bytes : null, name: b && b.name }; })()`);
let ab1ok = false, ab1d = { bidTotal: ab1.bidTotal };
if (ab1.bytes) { const sh = sheets(ab1.bytes); const recap = cells(sh[0] || ''), lines = cells(sh[1] || ''); const money = (s) => +String(s).replace(/[$,]/g, ''); const totalRow = recap.find(r => r.A && /^total$/i.test(r.A.t || '')); const headers = recap[0] ? Object.values(recap[0]).map(x => x.t).join('|') : ''; const lineHeaders = lines[0] ? Object.values(lines[0]).map(x => x.t).join('|') : '';
  const xlsxTotal = totalRow ? (Object.values(totalRow).map(x => x.v).filter(v => v != null).pop()) : null; const formulas = [...recap, ...lines].filter(r => Object.values(r).some(x => x.f)).length; const costWords = /material|labor|equipment|cost|markup|overhead|profit/i.test(headers + '|' + lineHeaders);
  const amountCol = lines[0] ? Object.keys(lines[0]).find(k => /amount/i.test(lines[0][k].t || '')) : null; const amounts = amountCol ? lines.slice(1).filter(r => r.C && r.C.t && !(r[amountCol] && r[amountCol].f)).map(r => r[amountCol] && r[amountCol].v).filter(v => typeof v === 'number') : []; /* line rows only: a description and no formula */ const amountSum = Math.round(amounts.reduce((a, b) => a + b, 0) * 100) / 100;
  ab1d = { bidTotal: ab1.bidTotal, xlsxTotal, headers, lineHeaders, formulas, costWords, amountSum, lineCount: amounts.length, bidRowCount: ab1.bidRows.length };
  ab1ok = xlsxTotal != null && Math.abs(xlsxTotal - money(ab1.bidTotal)) < 0.005 && !costWords && formulas >= 2 && Math.abs(amountSum - money(ab1.bidTotal)) < 0.005; }
check('AB1 the client review .xlsx carries SELL: its total equals the bid Total, its line amounts sum to it, no cost/margin column appears on a client-named file, and the sums are live formulas', ab1ok, ab1d);
// AB2 — the takeoff file names the library it was priced with; a mismatch is said, a match is silent
const ab2 = await ev(`(async () => { const snap = VESApp.snapshot(); const lib = snap.library; const sellA = +VESApp.recapModel().sell.toFixed(2);
  loadFromData.confirmed = true; VESApp.loadFromData(JSON.parse(JSON.stringify(snap))); await new Promise(r => setTimeout(r, 400)); const bannerSame = [...document.querySelectorAll('.banner .msg')].map(b => b.textContent).filter(t => /librar/i.test(t)).length; const sellB = +VESApp.recapModel().sell.toFixed(2);
  const other = JSON.parse(JSON.stringify(snap)); if (other.library) { other.library.fingerprint = 'deadbeef'; other.library.name = 'Some other price book'; } VESApp.loadFromData(other); await new Promise(r => setTimeout(r, 400)); const bannerDiff = [...document.querySelectorAll('.banner .msg')].map(b => b.textContent).filter(t => /librar/i.test(t)); const toast = document.getElementById('toast').textContent;
  return { lib, sellA, sellB, bannerSame, bannerDiff, toast }; })()`);
check('AB2 the takeoff file carries the library name + fingerprint; loading it under the same library is silent and cent-identical; a different fingerprint raises a standing banner that names both', ab2.lib && typeof ab2.lib.fingerprint === 'string' && ab2.lib.fingerprint.length >= 8 && ab2.sellA === ab2.sellB && ab2.bannerSame === 0 && ab2.bannerDiff.length === 1 && /Some other price book/.test(ab2.bannerDiff[0]), ab2);
// AB3 — the estimate CSV shows the ladder and it sums
const ab3 = await ev(`(() => { window.__blobs.length = 0; exportGridCSV(); const b = window.__blobs.find(x => /estimate-grid\\.csv$/.test(x.name)); return b ? b.bytes : null; })()`);
let ab3ok = false, ab3d = {};
if (ab3) { const txt = typeof ab3 === 'string' ? ab3 : Buffer.from(ab3).toString('utf8'); const lines = txt.split(/\r?\n/).filter(Boolean); const foot = {}; for (const l of lines) { const f = l.split(','); const label = f[2]; if (/^(Cost|Overhead|Markup|Profit|Sell)/.test(label || '')) foot[label.split(' ')[0]] = +f[6]; } ab3d = foot; ab3ok = ['Cost', 'Overhead', 'Markup', 'Profit', 'Sell'].every(k => typeof foot[k] === 'number') && Math.abs(foot.Cost + foot.Overhead + foot.Markup + foot.Profit - foot.Sell) < 0.005; }
check('AB3 the estimate CSV footer carries Cost, Overhead, Markup, Profit and Sell, and Cost + the three ladder rows equals Sell to the cent', ab3ok, ab3d);
// AB4 — the audit trail is named where a buyer reads
const landing = await ev(`(document.getElementById('empty') || document.body).textContent.replace(/\\s+/g, ' ')`);
const readme = readFileSync(join(ROOT, 'README.md'), 'utf8').replace(/\s+/g, ' ');
check('AB4 the landing and the README name the audit trail (who measured, which sheet, what calibration)', /audit/i.test(landing) && /sheet/i.test(landing) && /audit/i.test(readme) && /calibrat/i.test(readme), { landingHasAudit: /audit/i.test(landing), readmeHasAudit: /audit/i.test(readme) });
const fails = results.filter(r => !r.ok).length; console.log(`\nprobe-ab: ${results.length - fails}/${results.length} passed, ${fails} failed`); c.close(); chrome.kill('SIGKILL'); process.exit(fails ? 1 : 0);
