// Batch AE gate — PRINT TAKEOFF: the marked-up sheet with every measured quantity and nothing priced (owner's word,
// 2026-09-04 chat: "it should be print takeoff only … you choose"). RED-first on F18.67: no such door existed; the bid
// door's own comment said "print the sheet separately" while no path did; Ctrl+P on the sheet printed the last bid.
//   node tools/sweep/probe-ae.mjs <ves.html> <demo.json> <plan.pdf> <repo root>     exit 0 pass / 1 findings / 2 harness
import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { inflateSync } from 'node:zlib';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, DEMO, PLAN] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, close() { ws.close(); } })); ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } }); }); }
const port = 9100 + Math.floor(Math.random() * 40); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-pae-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable');
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + JSON.stringify(detail) : '')); };
const demo = readFileSync(DEMO, 'utf8'); const pdfB64 = readFileSync(PLAN).toString('base64');
const arm = `window.__printed = 0; window.print = () => { window.__printed++; }; window.__demo = ${demo}; loadFromData.confirmed = true; 1`;
async function load() { await c.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }); await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await ev(`localStorage.clear(); ${arm}`); await sleep(300); }
const pdfFillsAndPages = async () => { const { data } = await c.send('Page.printToPDF', { printBackground: false, preferCSSPageSize: true }); const txt = Buffer.from(data, 'base64').toString('latin1'); const rg = new Set(); let m; const re = /stream\r?\n([\s\S]*?)endstream/g; while ((m = re.exec(txt)) !== null) { let dec; try { dec = inflateSync(Buffer.from(m[1], 'latin1')).toString('latin1'); } catch (_) { dec = m[1]; } for (const mm of dec.matchAll(/([0-9.]+) ([0-9.]+) ([0-9.]+) rg/g)) rg.add(mm.slice(1, 4).map((x) => (+x).toFixed(2)).join(',')); } const counts = [...txt.matchAll(/\/Type\s*\/Pages[^>]*?\/Count\s+(\d+)/g)].map((x) => +x[1]); return { fills: [...rg], pages: Math.max(0, ...counts), bytes: txt.length }; };
const latch = `(() => { const d = document.getElementById('printDoc'); const t = d.innerHTML.replace(/<img[^>]*>/g, ' ').replace(/<[^>]+>/g, ' ').replace(/&amp;/g, '&').replace(/\\s+/g, ' ').trim(); /* tags → spaces so adjacent cells keep a boundary */ return { text: t.slice(0, 4000), img: /<img src="data:image\\/png/.test(d.innerHTML), swatches: d.querySelectorAll('.sw').length, rows: d.querySelectorAll('table tr').length, money: /\\$\\s?\\d/.test(t) || /\\b(Cost|Sell|Overhead|Markup|Profit|Unit price|Amount|Total)\\b/.test(t), toast: document.getElementById('toast').textContent, printed: window.__printed }; })()`;
await load();
// --- traced plan: TPO field polygon + drip edge line, identity set
const traced = await ev(`(async () => { const u8 = new Uint8Array(await (await fetch('data:application/pdf;base64,${pdfB64}')).arrayBuffer()); await VESApp.openFromBytes(u8, 'synthetic-plan.pdf'); let w = 0; while (!VESApp.AP().viewport && w < 30000) { await new Promise(r => setTimeout(r, 50)); w += 50; } await new Promise(r => setTimeout(r, 300));
  VESApp.applyScaleCalibration(VESApp.parseScale('1/8" = 1\\''), 1); VESApp.loadAssembly('tpo'); await new Promise(r => requestAnimationFrame(() => setTimeout(r, 120)));
  const p = VESApp.AP(); const o = p.els.overlay; const rect = o.getBoundingClientRect(); const pt = (x, y) => { const [vx, vy] = p.viewport.convertToViewportPoint(x, y); return { x: rect.left + vx, y: rect.top + vy }; }; const clickAt = (q) => o.dispatchEvent(new MouseEvent('click', { bubbles: true, clientX: q.x, clientY: q.y }));
  VESApp.activateCondition(VESApp.state.conditions.find(x => x.libRef === 'tpo.field')); await new Promise(r => setTimeout(r, 80)); for (const q of [pt(1500, 300), pt(2300, 300), pt(2300, 1400), pt(1500, 1400)]) clickAt(q); VESApp.finishDraft(); await new Promise(r => setTimeout(r, 120));
  VESApp.activateCondition(VESApp.state.conditions.find(x => x.libRef === 'tpo.dripedge')); await new Promise(r => setTimeout(r, 80)); for (const q of [pt(300, 1500), pt(1300, 1500)]) clickAt(q); VESApp.finishDraft(); await new Promise(r => setTimeout(r, 120));
  VESApp.setProjectMeta({ name: 'Synthetic takeoff', client: 'Synthetic Client', preparedBy: { company: 'Synthetic Roofing LLC', name: 'A. Estimator' } }); await new Promise(r => setTimeout(r, 200));
  const roll = VESCore.rollup(VESApp.state.conditions, VESApp.state.measurements); const byId = Object.fromEntries(VESApp.state.conditions.map(c => [c.id, c]));
  return { measured: roll.filter(r => r.count > 0).map(r => ({ name: r.name, qty: VESCore.fmtQty(dispQtyOf(r, byId[r.id]).qty), unit: displayUnit(r.unit), color: byId[r.id].color })), sell: VESApp.recapModel().sell }; })()`);
// AE1 — a door in the exports menu and the command palette
const doors = await ev(`(async () => { setDataMenu(true); await new Promise(r => setTimeout(r, 100)); const b = document.getElementById('btnMenuTakeoff'); const menu = b ? { text: b.textContent.replace(/\\s+/g, ' ').trim(), visible: b.getBoundingClientRect().width > 0 } : null; setDataMenu(false); openCmd(); await new Promise(r => setTimeout(r, 100)); const pal = [...document.querySelectorAll('#cmdList *')].map(e => e.textContent).some(t => /print takeoff/i.test(t)); closeCmd(); return { menu, pal }; })()`);
check('AE1 Files & exports carries a "Print takeoff…" door and the command palette lists it', doors.menu && doors.menu.visible && /print takeoff/i.test(doors.menu.text) && doors.pal, doors);
// AE2 — the paper: sheet snapshot with legend, every measured quantity as the app displays it, the print fires, the toast names itself
await ev(`(async () => { const b = document.getElementById('btnMenuTakeoff'); if (b) b.click(); else if (typeof printTakeoffDoc === 'function') printTakeoffDoc(); await new Promise(r => setTimeout(r, 2500)); return 1; })()`);
const L1 = await ev(latch);
const allQty = traced.measured.every((m) => L1.text.includes(m.qty + ' ' + m.unit) && L1.text.includes(m.name));
check('AE2 the takeoff paper carries the plan snapshot, its legend swatches, and every measured condition with the quantity the app displays; the print fires and the toast names it', L1.img && L1.swatches >= 2 && allQty && L1.printed === 1 && /takeoff sent to print/i.test(L1.toast), { img: L1.img, swatches: L1.swatches, allQty, expected: traced.measured, printed: L1.printed, toast: L1.toast });
// AE3 — no money on it
check('AE3 no money on the takeoff paper: no $ figure and none of Cost / Sell / Overhead / Markup / Profit / Unit price / Amount / Total', !L1.money, { money: L1.money, sample: L1.text.slice(0, 300) });
// AE4 — printed bytes: the swatch colours survive with background graphics OFF, at least one page
const pdf = await pdfFillsAndPages();
const wantFills = traced.measured.map((m) => { const h = m.color.replace('#', ''); return [0, 2, 4].map((i) => (parseInt(h.slice(i, i + 2), 16) / 255).toFixed(2)).join(','); });
check('AE4 print-to-PDF of the takeoff (background graphics off): ≥ 1 page and both condition colours present in the content streams', pdf.pages >= 1 && wantFills.every((f) => pdf.fills.includes(f)), { pages: pdf.pages, bytes: pdf.bytes, wantFills, got: pdf.fills.slice(0, 12) });
// AE5 — typed-only takeoff: tables still print, no snapshot, no money; nothing measured: the latch is released and the door says so
await load();
const typed = await ev(`(async () => { VESApp.loadFromData(window.__demo); await new Promise(r => setTimeout(r, 500)); const b = document.getElementById('btnMenuTakeoff'); if (b) b.click(); else if (typeof printTakeoffDoc === 'function') printTakeoffDoc(); await new Promise(r => setTimeout(r, 1200)); return ${latch}; })()`);
await load();
const empty = await ev(`(async () => { const b = document.getElementById('btnMenuTakeoff'); if (b) b.click(); else if (typeof printTakeoffDoc === 'function') printTakeoffDoc(); await new Promise(r => setTimeout(r, 600)); return ${latch}; })()`);
check('AE5 typed-only takeoff prints its quantity tables (3,150.8 SF · 240 LF) with no money and no snapshot; with nothing measured the latch is released and the door says so', typed.text.includes('3,150.8 SF') && typed.text.includes('240 LF') && !typed.money && !typed.img && typed.printed === 1 && empty.printed === 0 && /nothing measured/i.test(empty.toast) && /Nothing to print/.test(empty.text), { typed: { img: typed.img, money: typed.money, printed: typed.printed, has: [typed.text.includes('3,150.8 SF'), typed.text.includes('240 LF')] }, empty: { printed: empty.printed, toast: empty.toast, text: empty.text.slice(0, 80) } });
const fails = results.filter((r) => !r.ok).length; console.log(`\nprobe-ae: ${results.length - fails}/${results.length} passed, ${fails} failed`); c.close(); chrome.kill('SIGKILL'); process.exit(fails ? 1 : 0);
