// Batch AI gate — the two dropdowns in trade words (Patrick's rulings P3-R2 + P3-R3, 2026-09-03). RED-first on F18.70.
// args: <VES_PM.html> <demo.json> <repo root>
import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, DEMO, ROOT] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, close() { ws.close(); } })); ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } }); }); }
const port = 9100 + Math.floor(Math.random() * 40); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-pai-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable');
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + JSON.stringify(detail) : '')); };
const demo = readFileSync(DEMO, 'utf8');
await c.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }); await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); }
await ev(`localStorage.clear(); window.__demo = ${demo}; loadFromData.confirmed = true; window.confirmDocumentSwap = () => Promise.resolve(true); window.__blobs = []; window.saveBlob = (name, bytes, mime) => { window.__blobs.push({ name, size: (bytes && bytes.length) || 0 }); }; VESApp.loadFromData(window.__demo); 1`); await sleep(600);
// AI1 — four plain sections, no AI-speak in the menu
const menu = await ev(`(async () => { setDataMenu(true); await new Promise(r => setTimeout(r, 100)); const secs = [...document.querySelectorAll('#dataMenu .menu-sec')].map(e => e.textContent.trim()); const items = [...document.querySelectorAll('#dataMenu button')].map(b => ({ id: b.id, text: b.textContent.replace(/\\s+/g, ' ').trim(), title: b.title || '' })); setDataMenu(false); return { secs, items }; })()`);
const jargon = /breath|notebook|shared-driver|provenance|register|door|latch|sliver|lens/i;
const bad = menu.items.filter(i => jargon.test(i.text) || jargon.test(i.title)).map(i => i.id);
check('AI1 the exports menu reads Project · Print · Spreadsheets · Settings and none of its words are seat-speak', JSON.stringify(menu.secs) === JSON.stringify(['Project', 'Print', 'Spreadsheets', 'Settings']) && bad.length === 0, { secs: menu.secs, jargonIn: bad, items: menu.items.map(i => i.text).slice(0, 14) });
// AI2 — the working CSVs live under Setup, and still export
const csvs = await ev(`(async () => { const inMenu = ['btnCSVBOM', 'btnCSVRoll', 'btnCSVAudit'].filter(id => document.querySelector('#dataMenu #' + id)); const inSetup = ['btnCSVBOM', 'btnCSVRoll', 'btnCSVAudit'].filter(id => document.querySelector('#asmModal #' + id)); VESApp.openAssemblies(); await new Promise(r => setTimeout(r, 200)); window.__blobs.length = 0; const got = []; for (const id of ['btnCSVBOM', 'btnCSVRoll', 'btnCSVAudit']) { const b = document.getElementById(id); if (b && !b.disabled) { b.click(); await new Promise(r => setTimeout(r, 200)); } got.push({ id, present: !!b, disabled: b ? b.disabled : null, visible: b ? b.getBoundingClientRect().width > 0 : false }); } const files = window.__blobs.map(x => x.name); VESApp.closeAssemblies(); return { inMenu, inSetup, got, files }; })()`);
check('AI2 bill of materials, condition totals and audit CSVs are gone from the menu, live in Setup, and each still writes a file', csvs.inMenu.length === 0 && csvs.inSetup.length === 3 && csvs.got.every(g => g.present && g.visible) && csvs.files.some(f => /bom|materials/i.test(f)) && csvs.files.some(f => /rollup|totals/i.test(f)) && csvs.files.some(f => /audit/i.test(f)), csvs);
// AI3 — the rack has no Type group; clicking a condition still decides the tool and a polygon still lands
const rack = await ev(`(async () => { const gone = ['btnToolLinear', 'btnToolArea', 'btnToolCount'].filter(id => document.getElementById(id)); const secs = [...document.querySelectorAll('#rack .rack-sec')].map(e => e.textContent.trim()); const st = VESApp.state; const area = st.conditions.find(x => x.type === 'area'); const n0 = st.measurements.length; VESApp.activateCondition(area); await new Promise(r => setTimeout(r, 100)); const tool = st.tool, armedType = st.activeCond && st.activeCond.type; st.draft = { points: [{ x: 10, y: 10 }, { x: 60, y: 10 }, { x: 60, y: 50 }, { x: 10, y: 50 }] }; VESApp.finishDraft(); await new Promise(r => setTimeout(r, 200)); const n1 = st.measurements.length; const last = st.measurements[st.measurements.length - 1]; document.getElementById('btnRect').click(); await new Promise(r => setTimeout(r, 100)); return { gone, secs, tool, armedType, added: n1 - n0, lastType: last && last.type, lastValue: last && last.value, rectMode: st.rectMode, rectArmed: document.getElementById('btnRect').classList.contains('armed') }; })()`);
check('AI3 no Linear / Area / Count buttons on the rack; clicking an area condition arms the area tool, a polygon still lands, Rect still switches the shape', rack.gone.length === 0 && !rack.secs.includes('Type') && rack.tool === 'measure' && rack.armedType === 'area' && rack.added === 1 && rack.lastType === 'area' && rack.lastValue > 0 && rack.rectMode === true && rack.rectArmed, rack);
// AI4 — Setup speaks plain words
const setup = await ev(`(() => { const m = document.getElementById('asmModal'); const heads = [...m.querySelectorAll('h3, h4, summary')].map(e => e.textContent.trim()); return { heads, legend: (typeof AUTH_LEGEND === 'string') ? AUTH_LEGEND : null, intro: (m.querySelector('p') || {}).textContent || '' }; })()`);
const wantHeads = ['Working files', 'Bill of materials', 'Price library', 'Add a priced item to a system', 'Add a line by hand'];
const oldHeads = /owned library|author —|manual line —|\(raw\)/i;
check('AI4 Setup headings read Working files · Bill of materials · Price library · Add a priced item · Add a line by hand; the price-source legend is plain', wantHeads.every(w => setup.heads.some(h => h.startsWith(w))) && !setup.heads.some(h => oldHeads.test(h)) && /^Price source/.test(setup.legend || '') && !/AUTH —/.test(setup.legend || ''), setup);
// AI5 — the Estimate lens's buttons name the same files
const est = await ev(`(() => ({ grid: document.getElementById('gExportGrid').textContent.trim(), gridTitle: document.getElementById('gExportGrid').title, roll: document.getElementById('gExportRoll').textContent.trim() }))()`);
check('AI5 the Estimate lens buttons read "Estimate CSV" and "Condition totals CSV" and say they are the same files', /Estimate CSV/.test(est.grid) && /same file/i.test(est.gridTitle) && /Condition totals/.test(est.roll), est);
const fails = results.filter(r => !r.ok).length; console.log(`\nprobe-ai: ${results.length - fails}/${results.length} passed, ${fails} failed`); c.close(); chrome.kill('SIGKILL'); process.exit(fails ? 1 : 0);
