// Batch AE gate — the takeoff prints (Patrick, 2026-09-03: "there is no way to just print a takeoff"). RED-first on F18.66.
// args: <VES_PM.html> <demo.json> <plan-2page.pdf> <repo root> [prior build html — AE7 compares the proposal snapshot byte for byte]
import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, DEMO, PDF, ROOT, PRIOR] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, close() { ws.close(); } })); ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } }); }); }
const port = 9100 + Math.floor(Math.random() * 40); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-pae-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable');
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const results = []; const check = (name, ok, detail) => { results.push({ name, ok: !!ok }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail !== undefined ? '  ' + JSON.stringify(detail) : '')); };
const demo = readFileSync(DEMO, 'utf8'); const pdfB64 = readFileSync(PDF).toString('base64');
const arm = `window.print = () => { window.__printed = (window.__printed || 0) + 1; }; window.__demo = ${demo}; loadFromData.confirmed = true; window.confirmDocumentSwap = () => Promise.resolve(true); window.__blobs = []; window.saveBlob = (name, bytes, mime) => { window.__blobs.push({ name, mime }); }; 1`;
async function load(path) { await c.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false }); await c.send('Page.navigate', { url: 'file://' + path }); for (let i = 0; i < 400; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); } await ev(`localStorage.clear(); ${arm}`); }
const tryEv = async (expr) => { try { return await ev(expr); } catch (e) { return { error: String(e.message || e).slice(0, 160) }; } };
await load(VES);
// AE1 — the exports menu carries the door
const menu = await ev(`(async () => { setDataMenu(true); await new Promise(r => setTimeout(r, 100)); const b = document.getElementById('btnMenuTakeoff'); const out = b ? { text: b.textContent.replace(/\\s+/g, ' ').trim(), visible: b.getBoundingClientRect().width > 0 } : null; setDataMenu(false); return out; })()`);
check('AE1 the exports menu lists the takeoff beside the other print doors', !!menu && menu.visible && /takeoff/i.test(menu.text), menu);   // AI: the Print section reads "Takeoff…" 
// a two-page synthetic plan, one library assembly, measurements on both pages (values set directly; the pages are not calibrated, so the print must not depend on calibration)
const setup = await tryEv(`(async () => { const bin = atob('${pdfB64}'); const u8 = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i); await VESApp.openFromBytes(u8, 'synthetic-plan.pdf'); let w = 0; while (!VESApp.AP().viewport && w < 30000) { await new Promise(r => setTimeout(r, 50)); w += 50; } VESApp.loadAssembly('tpo'); await new Promise(r => setTimeout(r, 200)); const st = VESApp.state; const area = st.conditions.find(c => c.type === 'area'), lin = st.conditions.find(c => c.type === 'linear'), cnt = st.conditions.find(c => c.type === 'count'); st.measurements.push({ id: 9001, conditionId: area.id, page: 1, type: 'area', points: [{x:300,y:300},{x:1300,y:300},{x:1300,y:900},{x:300,y:900}], value: 7000, notes: '', manual: false }, { id: 9002, conditionId: lin.id, page: 2, type: 'linear', points: [{x:400,y:400},{x:1400,y:400}], value: 100, notes: '', manual: false }, { id: 9003, conditionId: cnt.id, page: 2, type: 'count', points: [{x:500,y:600},{x:700,y:600},{x:900,y:600}], value: 3, notes: '', manual: false }); VESApp.renderCards(); await new Promise(r => setTimeout(r, 300)); return { pages: st.numPages, area: area.name, lin: lin.name, cnt: cnt.name }; })()`);
const printed = await tryEv(`(async () => { window.__printed = 0; document.getElementById('toast').textContent = ''; await VESApp.printTakeoff(); await new Promise(r => setTimeout(r, 150)); const d = document.getElementById('printDoc'); const sheets = [...d.querySelectorAll('.tk-sheet')]; const out = []; for (const s of sheets) { const img = s.querySelector('img'); let nw = 0; if (img) { try { await img.decode(); } catch (_) {} nw = img.naturalWidth; } out.push({ head: (s.querySelector('h2') || {}).textContent || '', png: !!(img && /^data:image\\/png/.test(img.src)), naturalWidth: nw, legend: (s.querySelector('.plegend') || {}).textContent || '' }); } const rows = [...d.querySelectorAll('.tk-qty tbody tr')].map(tr => [...tr.children].map(td => td.textContent.trim())); const cards = [...document.querySelectorAll('#cards .card')].map(cd => ({ name: cd.querySelector('.name').textContent.replace(/^[▸▾]\\s*/, '').trim(), qty: (cd.querySelector('.qty') || {}).textContent || '' })); return { sheets: out, rows, cards, text: d.textContent, printed: window.__printed, toast: document.getElementById('toast').textContent, ftin: VESApp.core.formatFtIn(100) }; })()`);
const S2 = printed.sheets || [];
check('AE2 one landscape sheet section per page carrying measurements, each with a decoded PNG of the whole sheet (width > 400)', S2.length === 2 && S2.every(s => s.png && s.naturalWidth > 400) && /Sheet 1 of 2/.test(S2[0].head) && /Sheet 2 of 2/.test(S2[1].head), printed.error || S2.map(s => ({ head: s.head, png: s.png, w: s.naturalWidth })));
const lg = (i, name) => !!(S2[i] && name && S2[i].legend.includes(name));
check('AE3 each sheet legend names exactly the conditions drawn on that sheet, with that sheet\'s quantity', lg(0, setup.area) && !lg(0, setup.lin) && lg(1, setup.lin) && lg(1, setup.cnt) && !lg(1, setup.area) && /7000\.0 SF/.test(S2[0]?.legend || '') && /3 EA/.test(S2[1]?.legend || ''), printed.error || S2.map(s => s.legend));
const rows = printed.rows || []; const row = (name) => rows.find(r => r[0] && r[0].includes(name));
const rA = row(setup.area), rL = row(setup.lin), rC = row(setup.cnt);
const cardQty = (name) => { const cd = (printed.cards || []).find(x => x.name === name); return cd ? cd.qty : ''; };
const qtyOk = rA && rL && rC && rA[3] === '7000.0' && rL[3] === printed.ftin && rC[3] === '3' && cardQty(setup.area).startsWith('7000.0') && cardQty(setup.lin).startsWith(printed.ftin) && cardQty(setup.cnt).startsWith('3');
check('AE4 the closing quantities page carries the card numbers (area, linear ft-in, count) and the sheets each condition sits on', !!qtyOk && rA[2] === '1' && rL[2] === '2' && rC[2] === '2', printed.error || { rows, cards: printed.cards });
check('AE5 no money anywhere on the takeoff; print called once; the toast names the takeoff', typeof printed.text === 'string' && !printed.text.includes('$') && printed.printed === 1 && /takeoff/i.test(printed.toast), printed.error || { hasDollar: (printed.text || '').includes('$'), printed: printed.printed, toast: printed.toast });
// AE8 — rendered bytes: the latched takeoff paginates as three landscape pages (two sheets + quantities) — Page.printToPDF on
// the app page itself under its own @media print rules. (Measured: a 3888 px sheet image ran this past 45 s; the product composes at 2000 px.)
let pdfPages = { error: 'not run' };
try { const t0 = Date.now(); const { data } = await Promise.race([c.send('Page.printToPDF', { printBackground: false, preferCSSPageSize: true }), new Promise((_, rej) => setTimeout(() => rej(new Error('printToPDF did not return within 60 s')), 60000))]); const txt = Buffer.from(data, 'base64').toString('latin1'); const boxes = [...txt.matchAll(/\/MediaBox\s*\[\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\]/g)].map(m => ({ w: Math.round(+m[3] - +m[1]), h: Math.round(+m[4] - +m[2]) })); pdfPages = { n: boxes.length, landscape: boxes.filter(b => b.w > b.h).length, ms: Date.now() - t0, boxes: boxes.slice(0, 4) }; } catch (e) { pdfPages = { error: String(e.message || e).slice(0, 120) }; }
check('AE8 the printed takeoff is three landscape pages (two sheets and the quantities page) in rendered PDF bytes, within 60 s', pdfPages.n === 3 && pdfPages.landscape === 3, pdfPages);
// AE6 — no sheet: the latch holds the release placeholder and nothing goes to print
await load(VES);
const none = await tryEv(`(async () => { window.__printed = 0; await VESApp.printTakeoff(); await new Promise(r => setTimeout(r, 100)); return { text: document.getElementById('printDoc').textContent.trim(), printed: window.__printed, toast: document.getElementById('toast').textContent }; })()`);
check('AE6 with no sheet open the takeoff door releases the print latch (placeholder text) and does not print', !none.error && /Nothing to print/.test(none.text) && none.printed === 0 && /open a plan|start a grid/i.test(none.toast), none);
// AE7 — the proposal's plan snapshot is unchanged by the shared compositor (byte-for-byte against the prior build on the demo)
// (the stock demo is typed quantities with no drawn points — the same two drawn shapes probe-v V4 adds give the snapshot something to frame)
const propExpr = `(async () => { const d = JSON.parse(JSON.stringify(window.__demo)); d.measurements = [{ id: 11, conditionId: 1, page: 1, type: 'area', points: [{x:20,y:20},{x:120,y:20},{x:120,y:90},{x:20,y:90}], value: 7000, notes: '', manual: false }, { id: 12, conditionId: 5, page: 1, type: 'linear', points: [{x:20,y:20},{x:120,y:20}], value: 100, notes: '', manual: false }]; VESApp.loadFromData(d); await new Promise(r => setTimeout(r, 600)); return await VESApp.proposalHTML(); })()`;
const propNew = await tryEv(propExpr);
if (PRIOR) { await load(PRIOR); const propOld = await tryEv(propExpr);
  const snap = (h) => { const m = /<figure class="pviz">[\s\S]*?<\/figure>/.exec(String(h)); return m ? m[0] : null; };
  check('AE7 the proposal\'s plan snapshot section is byte-identical to the prior build\'s on the demo', typeof propNew === 'string' && snap(propNew) != null && snap(propNew) === snap(propOld), { newLen: (snap(propNew) || '').length, oldLen: (snap(propOld) || '').length }); }
else check('AE7 the proposal still carries its plan snapshot (no prior build given to compare against)', typeof propNew === 'string' && /<figure class="pviz"><img src="data:image\/png/.test(propNew), { len: (propNew || '').length });
const fails = results.filter(r => !r.ok).length; console.log(`\nprobe-ae: ${results.length - fails}/${results.length} passed, ${fails} failed`); c.close(); chrome.kill('SIGKILL'); process.exit(fails ? 1 : 0);
