// Mobile feasibility, pass 2: a priced takeoff ON a real (synthetic) sheet, phone with the rail hidden, landscape phone,
// exports menu / project modal fit, proposal snapshot on the sheet, bid rows — all on the throttled phone profile.
import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const [VES, PDF, OUT] = process.argv.slice(2);
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); const ls = [];
  ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, on(f) { ls.push(f); }, close() { ws.close(); } }));
  ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } for (const f of ls) f(msg); }); }); }
const port = 9800 + Math.floor(Math.random() * 90); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-p5-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable'); const errs = [];
c.on((m) => { if (m.method === 'Runtime.exceptionThrown') errs.push((m.params.exceptionDetails.exception?.description || m.params.exceptionDetails.text).slice(0, 200)); });
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const pdfB64 = readFileSync(PDF).toString('base64'); const shot = async (n) => { const { data } = await c.send('Page.captureScreenshot', { format: 'png' }); writeFileSync(join(OUT, n + '.png'), Buffer.from(data, 'base64')); };
const tap = async (x, y) => { await c.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] }); await sleep(40); await c.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(150); };
async function setup(metrics, throttle) { errs.length = 0; await c.send('Emulation.setDeviceMetricsOverride', metrics); await c.send('Emulation.setTouchEmulationEnabled', { enabled: !!metrics.mobile, maxTouchPoints: 5 }); await c.send('Emulation.setCPUThrottlingRate', { rate: throttle });
  await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 600; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(50); }
  return ev(`(async () => { window.print = () => {}; const bin = atob('${pdfB64}'); const u8 = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i); await VESApp.openFromBytes(u8, 'synthetic-plan.pdf'); let w = 0; while (!VESApp.AP().viewport && w < 30000) { await new Promise(r => setTimeout(r, 50)); w += 50; }
    VESApp.applyScaleCalibration(VESApp.parseScale('1/8" = 1\\''), 1); VESApp.loadAssembly('tpo'); VESApp.addManualQuantity('tpo.field', 3150.8); VESApp.setProjectMeta({ name: 'Synthetic Field Review', client: 'Synthetic Client', preparedBy: { company: 'Synthetic Roofing Co', name: 'Sample Estimator' } });
    VESApp.state.assemblyProject.settings = { overheadPct: 10, markupPct: 8, profitPct: 5 }; VESApp.renderCards(); await new Promise(r => requestAnimationFrame(() => setTimeout(r, 200)));
    return { sell: +VESApp.recapModel().sell.toFixed(2), lines: VESApp.recapModel().lineCount }; })()`); }
async function traceDripEdge(label) {
  const tp = await ev(`(async () => { const App = VESApp; const cond = App.state.conditions.find(x => x.libRef === 'tpo.dripedge'); App.activateCondition(cond); await new Promise(r => setTimeout(r, 100)); const p = App.AP(); const rect = p.els.overlay.getBoundingClientRect(); const wrap = p.els.wrap.getBoundingClientRect(); const toCss = (pt) => { const [x, y] = p.viewport.convertToViewportPoint(pt.x, pt.y); return { x: rect.left + x, y: rect.top + y }; }; return { zoom: +p.zoom.toFixed(3), sheetCss: [Math.round(rect.width), Math.round(rect.height)], wrapCss: [Math.round(wrap.width), Math.round(wrap.height)], pts: [toCss({ x: 300, y: 1500 }), toCss({ x: 1300, y: 1500 })], innerW: innerWidth, innerH: innerHeight, ftPerCssPx: +((1 / p.viewport.scale) * App.state.calibrations[1].ftPerUnit).toFixed(2) }; })()`);
  const inView = tp.pts.every(p => p.x >= 0 && p.x < tp.innerW && p.y >= 0 && p.y < tp.innerH); let trace = null;
  if (inView) { await tap(tp.pts[0].x, tp.pts[0].y); await tap(tp.pts[1].x, tp.pts[1].y); trace = await ev(`(() => { const d = VESApp.state.draft && VESApp.state.draft.points.length; VESApp.finishDraft(); const m = VESApp.state.measurements[VESApp.state.measurements.length - 1]; return { draftPointsBeforeFinish: d, measurements: VESApp.state.measurements.length, valueFt: m && m.value != null && +m.value.toFixed(2), expectedFt: 111.11 }; })()`); }
  else await ev('VESApp.setTool("select")');
  return { ...tp, pointsInView: inView, trace };
}
async function surfaces(label) {
  const R = {};
  R.proposal = await ev(`(async () => { const t = performance.now(); const h = await VESApp.proposalHTML(); const d = new DOMParser().parseFromString(h, 'text/html'); const img = d.querySelector('.pviz img'); return { ms: Math.round(performance.now() - t), htmlKB: Math.round(h.length / 1024), snapshot: !!img, snapshotPngKB: img ? Math.round(img.getAttribute('src').length * 3 / 4 / 1024) : 0, failed: !!d.querySelector('.pviz-miss'), legend: [...d.querySelectorAll('.lgi')].map(l => l.textContent), sell: (d.querySelector('.big') || d.querySelector('tr.tot .n') || {}).textContent, toast: document.getElementById('toast').textContent }; })()`);
  R.bid = await ev(`(() => { printBidDoc(); const gate = document.getElementById('projModal').classList.contains('open'); document.getElementById('projModal').classList.remove('open'); if (gate) printBidDoc(); return { identityGateFired: gate, rows: document.querySelectorAll('#printDoc .divblock tbody tr').length, total: (document.querySelector('#printDoc .total-line .n') || {}).textContent }; })()`);
  R.exportsMenu = await ev(`(async () => { setDataMenu(true); await new Promise(r => setTimeout(r, 100)); const m = document.getElementById('dataMenu'); const r = m.getBoundingClientRect(); const items = [...m.querySelectorAll('button, a, [role=menuitem]')].filter(b => b.offsetParent); const out = { rect: { x: Math.round(r.x), y: Math.round(r.y), w: Math.round(r.width), h: Math.round(r.height) }, fits: r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight, items: items.length, smallestTargetPx: Math.min(...items.map(b => Math.round(b.getBoundingClientRect().height))) }; return out; })()`);
  await shot(label + '-exports'); await ev('setDataMenu(false)');
  R.projModal = await ev(`(async () => { VESApp.openProjModal(); await new Promise(r => setTimeout(r, 100)); const m = document.querySelector('#projModal .modal, #projModal > div') || document.getElementById('projModal'); const r = m.getBoundingClientRect(); const out = { rect: { x: Math.round(r.x), y: Math.round(r.y), w: Math.round(r.width), h: Math.round(r.height) }, fits: r.left >= 0 && r.right <= innerWidth && r.bottom <= innerHeight, inputs: m.querySelectorAll('input,textarea').length }; document.getElementById('projModal').classList.remove('open'); return out; })()`);
  R.estimate = await ev(`(async () => { VESApp.showEstimate(true); VESApp.renderEstimateGrid(); await new Promise(r => setTimeout(r, 200)); const t = document.querySelector('#estgridBody').closest('table'); const foot = document.getElementById('estgridFoot'); const inputs = [...document.querySelectorAll('#estgridBody input.recap-edit')]; const hs = inputs.map(i => Math.round(i.getBoundingClientRect().height)); return { rows: document.querySelectorAll('#estgridBody tr').length, tableWidth: Math.round(t.getBoundingClientRect().width), innerWidth, editableCells: inputs.length, cellHeightPx: hs.length ? Math.min(...hs) : null, foot: foot.textContent.replace(/\\s+/g, ' ').trim().slice(0, 100) }; })()`);
  await shot(label + '-estimate'); await ev('VESApp.showEstimate(false)');
  R.drawer = await ev(`(async () => { VESApp.openDrawer(); VESApp.setRecapTab('summary'); VESApp.renderRecap(); await new Promise(r => setTimeout(r, 200)); const b = document.getElementById('drawerBody'); const r = b.getBoundingClientRect(); const btns = [...b.querySelectorAll('button')].filter(x => x.offsetParent).map(x => ({ t: x.textContent.trim().slice(0, 18), fits: x.getBoundingClientRect().right <= innerWidth, h: Math.round(x.getBoundingClientRect().height) })); return { rect: { x: Math.round(r.x), y: Math.round(r.y), w: Math.round(r.width), h: Math.round(r.height) }, inViewport: r.top >= 0 && r.bottom <= innerHeight, buttons: btns, sellText: (document.querySelector('#drawerBody .sell, #drawerBody .rs-sell') || {}).textContent }; })()`);
  await shot(label + '-drawer'); await ev('VESApp.collapseDrawer()');
  R.autosave = await ev(`(async () => { markDirty(); await new Promise(r => setTimeout(r, 1200)); const ks = []; for (let i = 0; i < localStorage.length; i++) ks.push(localStorage.key(i)); return ks.filter(k => k.startsWith('ves:auto')).map(k => ({ k, kb: Math.round(localStorage.getItem(k).length / 1024) })); })()`);
  R.errors = errs.slice(); return R;
}
const out = {};
// Phone portrait, rail visible (rest state)
out.phoneRest = { ...(await setup({ width: 390, height: 844, deviceScaleFactor: 3, mobile: true }, 4)) }; out.phoneRest.trace = await traceDripEdge('phone-rest'); await shot('phone-rest-plan');
// Phone portrait, rail hidden (the app's own Hide control)
out.phoneRailHidden = await ev(`(async () => { VESApp.toggleRail(false); await new Promise(r => setTimeout(r, 300)); VESApp.fitToView(VESApp.AP()); let w = 0; while ((VESApp.AP().renderTask) && w < 20000) { await new Promise(r => setTimeout(r, 50)); w += 50; } await new Promise(r => setTimeout(r, 300)); const p = VESApp.AP(); const wr = p.els.wrap.getBoundingClientRect(); return { railOpen: VESApp.state.railOpen, wrapCss: [Math.round(wr.width), Math.round(wr.height)], zoom: +p.zoom.toFixed(3) }; })()`);
out.phoneRailHidden.trace = await traceDripEdge('phone-hidden'); await shot('phone-hidden-plan'); Object.assign(out.phoneRailHidden, await surfaces('phone-hidden'));
// Phone landscape
out.phoneLandscape = { ...(await setup({ width: 844, height: 390, deviceScaleFactor: 3, mobile: true }, 4)) }; out.phoneLandscape.trace = await traceDripEdge('phone-land'); await shot('phone-land-plan'); Object.assign(out.phoneLandscape, await surfaces('phone-land'));
// Tablet portrait for the same surfaces
out.tablet = { ...(await setup({ width: 820, height: 1180, deviceScaleFactor: 2, mobile: true }, 2)) }; out.tablet.trace = await traceDripEdge('tablet'); Object.assign(out.tablet, await surfaces('tablet'));
writeFileSync(join(OUT, 'probe5-report.json'), JSON.stringify(out, null, 1)); console.log(JSON.stringify(out, null, 1)); c.close(); chrome.kill('SIGKILL');
