import { spawn } from 'node:child_process'; import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { inflateSync } from 'node:zlib';
const CHROME = process.env.VES_CHROME; const sleep = (ms) => new Promise((r) => setTimeout(r, ms)); const VES = process.argv[2]; const OUT = process.argv[4];
function connect(url) { return new Promise((resolve, reject) => { const ws = new WebSocket(url); let id = 0; const pending = new Map(); const ls = [];
  ws.addEventListener('open', () => resolve({ send(m, p = {}) { return new Promise((res, rej) => { const mid = ++id; pending.set(mid, { res, rej }); ws.send(JSON.stringify({ id: mid, method: m, params: p })); }); }, on(f) { ls.push(f); }, close() { ws.close(); } }));
  ws.addEventListener('error', () => reject(new Error('ws'))); ws.addEventListener('message', (ev) => { const msg = JSON.parse(ev.data); if (msg.id && pending.has(msg.id)) { const { res, rej } = pending.get(msg.id); pending.delete(msg.id); msg.error ? rej(new Error(JSON.stringify(msg.error))) : res(msg.result); } for (const f of ls) f(msg); }); }); }
const port = 9900 + Math.floor(Math.random() * 90); const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${mkdtempSync(join(tmpdir(), 'ves-p3-'))}`, '--remote-allow-origins=*', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-first-run', 'about:blank'], { stdio: 'ignore' });
let wsUrl = null; for (let i = 0; i < 600 && !wsUrl; i++) { try { const l = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const p = l.find((t) => t.type === 'page'); if (p) wsUrl = p.webSocketDebuggerUrl; } catch (_) {} if (!wsUrl) await sleep(100); }
if (!wsUrl) { console.error('HARNESS FAIL: devtools target never appeared (Chrome did not start within 60 s)'); try { chrome.kill('SIGKILL'); } catch (_) {} process.exit(2); }
const c = await connect(wsUrl); await c.send('Page.enable'); await c.send('Runtime.enable'); const errs = [];
c.on((m) => { if (m.method === 'Runtime.exceptionThrown') errs.push((m.params.exceptionDetails.exception?.description || m.params.exceptionDetails.text).slice(0, 200)); if (m.method === 'Runtime.consoleAPICalled' && m.params.type === 'error') errs.push('console.error ' + m.params.args.map(a => a.value ?? a.description).join(' ').slice(0, 200)); });
const ev = async (expr) => { const { result, exceptionDetails } = await c.send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (exceptionDetails) throw new Error(exceptionDetails.exception?.description || exceptionDetails.text); return result.value; };
const demo = readFileSync(process.argv[3], 'utf8');
async function fresh() { errs.length = 0; await c.send('Page.navigate', { url: 'file://' + VES }); for (let i = 0; i < 200; i++) { try { if (await ev('document.readyState==="complete" && !!window.VESApp')) break; } catch (_) {} await sleep(100); } await ev(`window.print = () => { window.__printed = (window.__printed||0)+1; }; window.__demo = ${demo}; loadFromData.confirmed = true; 1`); }
const R = {};
// (a) audit on a clean grid takeoff, via the UI door
await fresh(); R.audit = await ev(`(async () => { VESApp.loadFromData(window.__demo); await new Promise(r => setTimeout(r, 400)); const btn = document.getElementById('btnVerify') || [...document.querySelectorAll('button')].find(b => /audit|check/i.test(b.textContent)); let clickErr = null; try { VESApp.openAudit(); } catch (e) { clickErr = String(e); } return { cal: VESApp.state.calibrations[1], clickErr, auditOpen: document.getElementById('audit').classList.contains('open'), auditText: document.getElementById('audit').textContent.slice(0, 120), doorButton: btn && (btn.id + ' "' + btn.textContent.trim() + '" visible=' + (btn.offsetParent !== null)) }; })()`); R.auditErrs = errs.slice();
// (b) ingress: string quantity, string pitch, null points
await fresh(); R.ingress = await ev(`(async () => { const d = JSON.parse(JSON.stringify(window.__demo)); d.measurements[0].value = "3150.8"; d.conditions[0].pitch = "1.2"; d.measurements.push({ id: 99, conditionId: 5, page: null, type: 'linear', points: null, value: 10, notes: '', manual: true });
  VESApp.loadFromData(d); await new Promise(r => setTimeout(r, 500)); const roll = VESCore.rollup(VESApp.state.conditions, VESApp.state.measurements); const eng = assemblyMeasured(); const m = VESApp.recapModel();
  return { rollupFieldQty: roll[0].quantity, rollupType: typeof roll[0].quantity, engineFieldQtyRaw: (eng.find(e => e.condId === 'tpo.field') || {}).value, engineFieldType: typeof (eng.find(e => e.condId === 'tpo.field') || {}).value, resolvedLines: VESApp.resolveAssembly().lines.length, recapSell: m.sell, recapLines: m.lineCount, hudSell: (document.querySelector('#hud') || {}).textContent?.replace(/\\s+/g, ' ').slice(0, 80), toast: document.getElementById('toast').textContent, banners: [...document.querySelectorAll('.banner .msg')].map(b => b.textContent.slice(0, 80)) }; })()`); R.ingressErrs = errs.slice();
// (c) injection sinks with hostile strings in a takeoff file + library
await fresh(); R.xss = await ev(`(async () => { window.__xss = []; const P = (t) => '<img src=x onerror="window.__xss.push(&quot;' + t + '&quot;)">'; const d = JSON.parse(JSON.stringify(window.__demo));
  d.projectMeta = { name: 'Job ' + P('projectMeta.name'), client: P('client'), address: P('address'), phone: P('phone'), email: P('email'), notes: P('notes'), preparedBy: { company: P('preparedBy.company'), name: P('preparedBy.name'), license: P('license'), phone: P('pbphone'), email: P('pbemail') }, proposalNotes: P('proposalNotes') };
  d.conditions[0].name = 'Cond ' + P('condition.name'); d.conditions[0].csi = P('condition.csi'); d.conditions[0].notes = P('condition.notes'); d.conditions[0].location = P('condition.location'); d.conditions[0].wbs = P('condition.wbs'); d.conditions[0].tags = [P('tag')]; d.conditions[1].color = 'red" onmouseover="window.__xss.push(1)';
  d.measurements[0].notes = P('measurement.notes'); d.assemblyProject.general = [{ id: 'g1', label: P('general.label'), qty: 1, unit: P('general.unit'), unit_cost: 5, csi: P('general.csi'), note: P('general.note') }]; d.pdfName = P('pdfName'); d.schedule = { rows: { 1: { start: 0, dur: 3 } } };
  VESApp.loadFromData(d); await new Promise(r => setTimeout(r, 500)); const steps = []; const step = async (n, f) => { try { await f(); await new Promise(r => setTimeout(r, 60)); } catch (e) { steps.push(n + ': threw ' + String(e).slice(0, 140)); } }; const raf = () => new Promise(r => requestAnimationFrame(() => setTimeout(r, 30)));
  await step('cards', async () => { VESApp.renderCards(); await raf(); }); await step('assembly', () => { VESApp.renderAssembly(); VESApp.openAssemblies(); VESApp.closeAssemblies(); }); await step('recapTabs', () => { for (const t of ['materials','labor','equipment','exceptions','estimate','summary']) VESApp.setRecapTab(t); });
  await step('grid', async () => { VESApp.showEstimate(true); VESApp.renderEstimateGrid(); await raf(); VESApp.showEstimate(false); }); await step('schedule', async () => { VESApp.showSchedule(true); VESApp.renderSchedule(); await raf(); VESApp.showSchedule(false); }); await step('ledger', () => VESApp.renderLedger()); await step('hud', () => { VESApp.renderHud(); VESApp.renderInspector(); });
  await step('projModal', () => { VESApp.openProjModal(); }); await step('bid', () => printBidDoc()); await step('bid2', () => printBidDoc()); await step('cost', () => printCostSheet()); await step('proposal', async () => { window.__ph = await VESApp.proposalHTML(); }); await step('clientReview', () => { window.__cr = VESApp.clientReviewHTML(); });
  await step('activate', async () => { VESApp.activateCondition(VESApp.state.conditions[0]); await raf(); }); await step('depth', async () => { VESApp.state.editingCondId = VESApp.state.conditions[0].id; VESApp.renderCards(); await raf(); }); await step('sheetStrip', () => renderSheetStrip()); await step('cmd', () => { VESApp.openCmd(); VESApp.closeCmd(); }); await step('resume', async () => { VESApp.flushAutosave(); renderResumeList(); await raf(); });
  await step('csvs', () => { const save = window.saveBlob; window.__csv = []; window.saveBlob = (n, t) => window.__csv.push(n); VESApp.exportRollupCSV(); VESApp.exportAuditCSV(); VESApp.exportBOMCSV(); exportGridCSV(); window.saveBlob = save; });
  await new Promise(r => setTimeout(r, 400)); const rawIn = (h) => !!h && /<img src=x onerror=/.test(h);
  return { fired: window.__xss, steps, proposalRaw: rawIn(window.__ph), clientReviewRaw: rawIn(window.__cr), bidRaw: rawIn(document.getElementById('printDoc').innerHTML), bodyRaw: rawIn(document.body.innerHTML), inlineHandlerAttrs: [...document.querySelectorAll('[onmouseover],[onerror],[onclick]')].length, styleAttrWithQuote: [...document.querySelectorAll('[style]')].filter(e => /onmouseover/.test(e.getAttribute('style'))).length, csvs: window.__csv }; })()`); R.xssErrs = errs.slice();
await fresh(); R.xssLib = await ev(`(async () => { window.__xss = []; const P = (t) => '<img src=x onerror="window.__xss.push(&quot;' + t + '&quot;)">'; const lib = JSON.parse(JSON.stringify(VESApp.state.library)); const cid = Object.keys(lib.conditions)[0]; lib.conditions[cid].label = 'L ' + P('lib.condition.label'); const iid = Object.keys(lib.items)[0]; lib.items[iid].desc = P('lib.item.desc'); lib.items[iid].note = P('lib.item.note'); const aid = Object.keys(lib.assemblies)[0]; lib.assemblies[aid].label = P('lib.assembly.label');
  let r; try { r = VESApp.importLibraryObject(lib, [{ id: 'gg', label: P('gen.label'), qty: 1, unit: 'LS', unit_cost: 1 }], 'hostile.json'); } catch (e) { r = 'threw ' + e; } VESApp.loadAssembly(aid); VESApp.addManualQuantity(cid, 10); await new Promise(res => requestAnimationFrame(() => setTimeout(res, 150))); VESApp.renderAssembly(); VESApp.openAssemblies(); VESApp.renderRecap(); VESApp.showEstimate(true); VESApp.renderEstimateGrid(); VESApp.showEstimate(false); VESApp.openProjModal(); printBidDoc(); printBidDoc(); printCostSheet(); await new Promise(res => setTimeout(res, 400)); return { importResult: r && r.ok !== undefined ? r.ok : r, fired: window.__xss, libProvText: (document.getElementById('libProv') || {}).textContent }; })()`); R.xssLibErrs = errs.slice();
// (d) proposal with a DRAWN polygon on the grid → legend swatches → print with and without background graphics
await fresh(); R.proposalDrawn = await ev(`(async () => { const d = JSON.parse(JSON.stringify(window.__demo)); d.measurements = [{ id: 11, conditionId: 1, page: 1, type: 'area', points: [{x:20,y:20},{x:120,y:20},{x:120,y:90},{x:20,y:90}], value: 7000, notes: '', manual: false }, { id: 12, conditionId: 5, page: 1, type: 'linear', points: [{x:20,y:20},{x:120,y:20}], value: 100, notes: '', manual: false }]; d.projectMeta.preparedBy = { company: 'Synthetic Roofing Co', name: 'Sample Estimator' };
  VESApp.loadFromData(d); await new Promise(r => setTimeout(r, 600)); const h = await VESApp.proposalHTML(); window.__ph = h; const doc = new DOMParser().parseFromString(h, 'text/html'); return { hasSheet: hasSheet(), hasSnapshot: !!doc.querySelector('.pviz img'), snapshotFailed: !!doc.querySelector('.pviz-miss'), legend: [...doc.querySelectorAll('.lgi')].map(l => ({ text: l.textContent, sw: l.querySelector('.sw').style.background })), caption: (doc.querySelector('figcaption') || {}).textContent, scope: [...doc.querySelectorAll('section.scope li')].map(li => li.textContent.trim()), investment: (doc.querySelector('.big') || {}).textContent, toast: document.getElementById('toast').textContent }; })()`);
async function pdfColors(html, printBackground) { const { targetId } = await c.send('Target.createTarget', { url: 'about:blank' }); const list = await (await fetch(`http://127.0.0.1:${port}/json`)).json(); const t = list.find((x) => x.id === targetId); const c2 = await connect(t.webSocketDebuggerUrl); await c2.send('Page.enable'); await c2.send('Page.navigate', { url: 'data:text/html;base64,' + Buffer.from(html).toString('base64') }); await sleep(800);
  const { data } = await c2.send('Page.printToPDF', { printBackground, preferCSSPageSize: true }); const buf = Buffer.from(data, 'base64'); writeFileSync(join(OUT, `proposal-bg${printBackground ? 'on' : 'off'}.pdf`), buf); const txt = buf.toString('latin1'); const rg = new Set(); let m; const re = /stream\r?\n([\s\S]*?)endstream/g; let pages = (txt.match(/\/Type\s*\/Page[^s]/g) || []).length;
  while ((m = re.exec(txt)) !== null) { let dec; try { dec = inflateSync(Buffer.from(m[1], 'latin1')).toString('latin1'); } catch (_) { dec = m[1]; } for (const mm of dec.matchAll(/([0-9.]+) ([0-9.]+) ([0-9.]+) rg/g)) rg.add(mm.slice(1, 4).map((x) => (+x).toFixed(2)).join(',')); } c2.close(); await c.send('Target.closeTarget', { targetId }); return { bytes: buf.length, pages, fillColors: [...rg] }; }
const ph = await ev('window.__ph'); R.proposalPrint = { backgroundGraphicsOn: await pdfColors(ph, true), backgroundGraphicsOff_chromeDefault: await pdfColors(ph, false) };
// (e) autosave contents + (f) schedule + (g) negative margin typed into the OH input
await fresh(); R.autosaveAndMargins = await ev(`(async () => { const d = JSON.parse(JSON.stringify(window.__demo)); d.projectMeta.client = 'SYNTH-CLIENT-MARKER'; d.projectMeta.address = '1 Synthetic Way'; VESApp.loadFromData(d); await new Promise(r => setTimeout(r, 300)); VESApp.setProjectMeta({ ...VESApp.state.projectMeta, phone: '000-000-0000' }); markDirty(); await new Promise(r => setTimeout(r, 1300));
  const keys = []; for (let i = 0; i < localStorage.length; i++) keys.push(localStorage.key(i)); const slots = keys.map(k => ({ k, bytes: localStorage.getItem(k).length, hasClient: /SYNTH-CLIENT-MARKER/.test(localStorage.getItem(k)), hasAddress: /Synthetic Way/.test(localStorage.getItem(k)) }));
  VESApp.showSchedule(true); VESApp.renderSchedule(); await new Promise(r => setTimeout(r, 100)); const sched = { rows: document.querySelectorAll('#schedBody .sched-row').length, meta: (document.getElementById('sMeta') || {}).textContent }; VESApp.showSchedule(false);
  const oh = document.getElementById('ohPct'); const before = VESApp.recapModel().sell; oh.value = '-5'; oh.dispatchEvent(new Event('input', { bubbles: true })); oh.dispatchEvent(new Event('change', { bubbles: true })); await new Promise(r => setTimeout(r, 200));
  const after = VESApp.recapModel(); return { slots, sched, negMargin: { inputValue: oh.value, validity: oh.validity.valid, storedOverheadPct: VESApp.state.assemblyProject.settings.overheadPct, ladderOh: after.oh, sellBefore: before, sellAfter: after.sell, toast: document.getElementById('toast').textContent, cue: (document.getElementById('gridCue') || {}).textContent } }; })()`); R.autosaveErrs = errs.slice();
writeFileSync(join(OUT, 'probe3-report.json'), JSON.stringify(R, null, 1)); console.log(JSON.stringify(R, null, 1)); c.close(); chrome.kill('SIGKILL');
